main: io.github.wolfleader116.chat.ChatPlugin
name: Chat
version: 3.3.4
description: Chat plugin
author: WolfLeader116
softdepend: [Vault,Settings,PlayerInfo,Utils]
commands:
  msg:
    description: Private message a player.
    aliases: [pm,message,whisper,tell,w,m,t]
  r:
    description: Reply to a private message.
    aliases: [reply]
  pl:
    description: Shows all custom plugins.
    aliases: [plugins]
  allpl:
    description: Shows all plugins.
    aliases: [allplugins]
    permission: chat.allplugins
  broadcast:
    description: Broadcasts a message to the entire server.
    aliases: [announce]
    permission: chat.broadcast
  global:
    description: Broadcasts a message to the entire server at a price or switches to the global channel.
    permission: chat.global
    aliases: [g]
  local:
    description: Broadcasts a message to the surrounding area.
    permission: chat.local
    aliases: [l]
  staff:
    description: Broadcasts a message to all staff.
    permission: chat.staff
    aliases: [s]
  nick:
    description: Gives the player a nickname.
    aliases: [nickname]
    permission: chat.nick
  chat:
    description: Shows chat plugin info.
permissions:
  chat.staff:
    description: Allows the player to use the staff command.
    default: op
  chat.local:
    description: Allows the player to use the local command.
    default: op
  chat.global:
    description: Allows the player to use the global command.
    default: op
  chat.allplugins:
    description: Allows the player to view all plugins.
    default: op
  chat.broadcast:
    description: Allows the player to broadcast to the entire server.
    default: op
  chat.nick:
    description: Allows the player to get a nickname.
    default: op
  chat.nick.other:
    description: Gives the player access to changing any nickname.
    default: op
    children:
      chat.nick: true
  chat.color:
    description: Lets the player put color codes in chat.
    default: op
  chat.allpl:
    description: Lets the player see all plugins.
    default: op
  chat.*:
    description: Gives the player all broadcast permissions.
    default: op
    children:
      chat.staff: true
      chat.local: true
      chat.global: true
      chat.allplugins: true
      chat.broadcast: true
      chat.nick: true
      chat.nick.other: true
      chat.color: true
      chat.allpl: true